#############################################################################
# Makefile for building: screenshot
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  screenshot.pro
# Template: app
# Command: /home/best/Qt5.7.0/5.7/gcc_64/bin/qmake -o Makefile screenshot.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DVERSION_STRING=\"0.3.0\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../5.7/gcc_64/include -I../../5.7/gcc_64/include/QtWidgets -I../../5.7/gcc_64/include/QtGui -I../../5.7/gcc_64/include/QtNetwork -I../../5.7/gcc_64/include/QtCore -I. -I. -I../../5.7/gcc_64/mkspecs/linux-g++
QMAKE         = /home/best/Qt5.7.0/5.7/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = screenshot0.3
DISTDIR = /home/best/Qt5.7.0/Workspace/screenshot/.tmp/screenshot0.3
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/best/Qt5.7.0/5.7/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/best/Qt5.7.0/5.7/gcc_64/lib -lQt5Widgets -L/usr/lib64 -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		form.cpp \
		successdialog.cpp moc_form.cpp \
		moc_successdialog.cpp
OBJECTS       = main.o \
		form.o \
		successdialog.o \
		moc_form.o \
		moc_successdialog.o
DIST          = ../../5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../5.7/gcc_64/mkspecs/common/unix.conf \
		../../5.7/gcc_64/mkspecs/common/linux.conf \
		../../5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../5.7/gcc_64/mkspecs/qconfig.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../5.7/gcc_64/mkspecs/features/spec_post.prf \
		../../5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../5.7/gcc_64/mkspecs/features/default_pre.prf \
		../../5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../5.7/gcc_64/mkspecs/features/default_post.prf \
		../../5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../5.7/gcc_64/mkspecs/features/qt.prf \
		../../5.7/gcc_64/mkspecs/features/resources.prf \
		../../5.7/gcc_64/mkspecs/features/moc.prf \
		../../5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		../../5.7/gcc_64/mkspecs/features/uic.prf \
		../../5.7/gcc_64/mkspecs/features/unix/thread.prf \
		../../5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../5.7/gcc_64/mkspecs/features/yacc.prf \
		../../5.7/gcc_64/mkspecs/features/lex.prf \
		screenshot.pro form.h \
		successdialog.h main.cpp \
		form.cpp \
		successdialog.cpp
QMAKE_TARGET  = screenshot
DESTDIR       = 
TARGET        = screenshot


first: all
####### Build rules

$(TARGET): ui_form.h ui_successdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: screenshot.pro ../../5.7/gcc_64/mkspecs/linux-g++/qmake.conf ../../5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../5.7/gcc_64/mkspecs/common/unix.conf \
		../../5.7/gcc_64/mkspecs/common/linux.conf \
		../../5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../5.7/gcc_64/mkspecs/qconfig.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../5.7/gcc_64/mkspecs/features/spec_post.prf \
		../../5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../5.7/gcc_64/mkspecs/features/default_pre.prf \
		../../5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../5.7/gcc_64/mkspecs/features/default_post.prf \
		../../5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../5.7/gcc_64/mkspecs/features/qt.prf \
		../../5.7/gcc_64/mkspecs/features/resources.prf \
		../../5.7/gcc_64/mkspecs/features/moc.prf \
		../../5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		../../5.7/gcc_64/mkspecs/features/uic.prf \
		../../5.7/gcc_64/mkspecs/features/unix/thread.prf \
		../../5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../5.7/gcc_64/mkspecs/features/yacc.prf \
		../../5.7/gcc_64/mkspecs/features/lex.prf \
		screenshot.pro \
		../../5.7/gcc_64/lib/libQt5Widgets.prl \
		../../5.7/gcc_64/lib/libQt5Gui.prl \
		../../5.7/gcc_64/lib/libQt5Network.prl \
		../../5.7/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile screenshot.pro
../../5.7/gcc_64/mkspecs/features/spec_pre.prf:
../../5.7/gcc_64/mkspecs/common/unix.conf:
../../5.7/gcc_64/mkspecs/common/linux.conf:
../../5.7/gcc_64/mkspecs/common/sanitize.conf:
../../5.7/gcc_64/mkspecs/common/gcc-base.conf:
../../5.7/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../5.7/gcc_64/mkspecs/common/g++-base.conf:
../../5.7/gcc_64/mkspecs/common/g++-unix.conf:
../../5.7/gcc_64/mkspecs/qconfig.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../5.7/gcc_64/mkspecs/features/qt_functions.prf:
../../5.7/gcc_64/mkspecs/features/qt_config.prf:
../../5.7/gcc_64/mkspecs/linux-g++/qmake.conf:
../../5.7/gcc_64/mkspecs/features/spec_post.prf:
../../5.7/gcc_64/mkspecs/features/exclusive_builds.prf:
../../5.7/gcc_64/mkspecs/features/default_pre.prf:
../../5.7/gcc_64/mkspecs/features/resolve_config.prf:
../../5.7/gcc_64/mkspecs/features/default_post.prf:
../../5.7/gcc_64/mkspecs/features/warn_on.prf:
../../5.7/gcc_64/mkspecs/features/qt.prf:
../../5.7/gcc_64/mkspecs/features/resources.prf:
../../5.7/gcc_64/mkspecs/features/moc.prf:
../../5.7/gcc_64/mkspecs/features/unix/opengl.prf:
../../5.7/gcc_64/mkspecs/features/uic.prf:
../../5.7/gcc_64/mkspecs/features/unix/thread.prf:
../../5.7/gcc_64/mkspecs/features/file_copies.prf:
../../5.7/gcc_64/mkspecs/features/testcase_targets.prf:
../../5.7/gcc_64/mkspecs/features/exceptions.prf:
../../5.7/gcc_64/mkspecs/features/yacc.prf:
../../5.7/gcc_64/mkspecs/features/lex.prf:
screenshot.pro:
../../5.7/gcc_64/lib/libQt5Widgets.prl:
../../5.7/gcc_64/lib/libQt5Gui.prl:
../../5.7/gcc_64/lib/libQt5Network.prl:
../../5.7/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile screenshot.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents form.h successdialog.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp form.cpp successdialog.cpp $(DISTDIR)/
	$(COPY_FILE) --parents form.ui successdialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_form.cpp moc_successdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_form.cpp moc_successdialog.cpp
moc_form.cpp: ../../5.7/gcc_64/include/QtWidgets/QWidget \
		../../5.7/gcc_64/include/QtWidgets/qwidget.h \
		../../5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../5.7/gcc_64/include/QtCore/qglobal.h \
		../../5.7/gcc_64/include/QtCore/qconfig.h \
		../../5.7/gcc_64/include/QtCore/qfeatures.h \
		../../5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../5.7/gcc_64/include/QtCore/qisenum.h \
		../../5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../5.7/gcc_64/include/QtCore/qlogging.h \
		../../5.7/gcc_64/include/QtCore/qflags.h \
		../../5.7/gcc_64/include/QtCore/qatomic.h \
		../../5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../5.7/gcc_64/include/QtCore/qmutex.h \
		../../5.7/gcc_64/include/QtCore/qnumeric.h \
		../../5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../5.7/gcc_64/include/QtCore/qnamespace.h \
		../../5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../5.7/gcc_64/include/QtCore/qobject.h \
		../../5.7/gcc_64/include/QtCore/qstring.h \
		../../5.7/gcc_64/include/QtCore/qchar.h \
		../../5.7/gcc_64/include/QtCore/qbytearray.h \
		../../5.7/gcc_64/include/QtCore/qrefcount.h \
		../../5.7/gcc_64/include/QtCore/qarraydata.h \
		../../5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../5.7/gcc_64/include/QtCore/qlist.h \
		../../5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../5.7/gcc_64/include/QtCore/qiterator.h \
		../../5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../5.7/gcc_64/include/QtCore/qpair.h \
		../../5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../5.7/gcc_64/include/QtCore/qstringlist.h \
		../../5.7/gcc_64/include/QtCore/qregexp.h \
		../../5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../5.7/gcc_64/include/QtCore/qmetatype.h \
		../../5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../5.7/gcc_64/include/QtCore/qmargins.h \
		../../5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../5.7/gcc_64/include/QtCore/qrect.h \
		../../5.7/gcc_64/include/QtCore/qsize.h \
		../../5.7/gcc_64/include/QtCore/qpoint.h \
		../../5.7/gcc_64/include/QtGui/qpalette.h \
		../../5.7/gcc_64/include/QtGui/qcolor.h \
		../../5.7/gcc_64/include/QtGui/qrgb.h \
		../../5.7/gcc_64/include/QtGui/qrgba64.h \
		../../5.7/gcc_64/include/QtGui/qbrush.h \
		../../5.7/gcc_64/include/QtCore/qvector.h \
		../../5.7/gcc_64/include/QtGui/qmatrix.h \
		../../5.7/gcc_64/include/QtGui/qpolygon.h \
		../../5.7/gcc_64/include/QtGui/qregion.h \
		../../5.7/gcc_64/include/QtCore/qdatastream.h \
		../../5.7/gcc_64/include/QtCore/qiodevice.h \
		../../5.7/gcc_64/include/QtCore/qline.h \
		../../5.7/gcc_64/include/QtGui/qtransform.h \
		../../5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../5.7/gcc_64/include/QtGui/qimage.h \
		../../5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../5.7/gcc_64/include/QtGui/qpixmap.h \
		../../5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../5.7/gcc_64/include/QtCore/qshareddata.h \
		../../5.7/gcc_64/include/QtCore/qhash.h \
		../../5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../5.7/gcc_64/include/QtGui/qfont.h \
		../../5.7/gcc_64/include/QtGui/qfontmetrics.h \
		../../5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../5.7/gcc_64/include/QtGui/qcursor.h \
		../../5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../5.7/gcc_64/include/QtGui/qevent.h \
		../../5.7/gcc_64/include/QtCore/qvariant.h \
		../../5.7/gcc_64/include/QtCore/qmap.h \
		../../5.7/gcc_64/include/QtCore/qdebug.h \
		../../5.7/gcc_64/include/QtCore/qtextstream.h \
		../../5.7/gcc_64/include/QtCore/qlocale.h \
		../../5.7/gcc_64/include/QtCore/qset.h \
		../../5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../5.7/gcc_64/include/QtCore/qurl.h \
		../../5.7/gcc_64/include/QtCore/qurlquery.h \
		../../5.7/gcc_64/include/QtCore/qfile.h \
		../../5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../5.7/gcc_64/include/QtGui/qvector2d.h \
		../../5.7/gcc_64/include/QtGui/qtouchdevice.h \
		../../5.7/gcc_64/include/QtCore/QDebug \
		../../5.7/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../../5.7/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../5.7/gcc_64/include/QtCore/QObject \
		../../5.7/gcc_64/include/QtNetwork/QSslConfiguration \
		../../5.7/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../../5.7/gcc_64/include/QtNetwork/qsslsocket.h \
		../../5.7/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../5.7/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../5.7/gcc_64/include/QtNetwork/qsslerror.h \
		../../5.7/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../5.7/gcc_64/include/QtCore/qcryptographichash.h \
		../../5.7/gcc_64/include/QtCore/qdatetime.h \
		../../5.7/gcc_64/include/QtNetwork/qssl.h \
		../../5.7/gcc_64/include/QtCore/QFlags \
		../../5.7/gcc_64/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../5.7/gcc_64/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../5.7/gcc_64/include/QtCore/QtGlobal \
		../../5.7/gcc_64/include/QtCore/QString \
		../../5.7/gcc_64/include/QtCore/QSharedDataPointer \
		../../5.7/gcc_64/include/QtCore/QMetaType \
		../../5.7/gcc_64/include/QtNetwork/QHttpMultiPart \
		../../5.7/gcc_64/include/QtNetwork/qhttpmultipart.h \
		../../5.7/gcc_64/include/QtCore/QByteArray \
		../../5.7/gcc_64/include/QtCore/QIODevice \
		../../5.7/gcc_64/include/QtNetwork/QNetworkRequest \
		../../5.7/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../../5.7/gcc_64/include/QtCore/QUrl \
		../../5.7/gcc_64/include/QtCore/QVariant \
		../../5.7/gcc_64/include/QtNetwork/QHttpPart \
		../../5.7/gcc_64/include/QtCore/QFile \
		../../5.7/gcc_64/include/QtNetwork/QNetworkReply \
		../../5.7/gcc_64/include/QtNetwork/qnetworkreply.h \
		../../5.7/gcc_64/include/QtNetwork/QSslSocket \
		form.h \
		../../5.7/gcc_64/bin/moc
	/home/best/Qt5.7.0/5.7/gcc_64/bin/moc $(DEFINES) -I/home/best/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++ -I/home/best/Qt5.7.0/Workspace/screenshot -I/home/best/Qt5.7.0/5.7/gcc_64/include -I/home/best/Qt5.7.0/5.7/gcc_64/include/QtWidgets -I/home/best/Qt5.7.0/5.7/gcc_64/include/QtGui -I/home/best/Qt5.7.0/5.7/gcc_64/include/QtNetwork -I/home/best/Qt5.7.0/5.7/gcc_64/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include form.h -o moc_form.cpp

moc_successdialog.cpp: ../../5.7/gcc_64/include/QtWidgets/QDialog \
		../../5.7/gcc_64/include/QtWidgets/qdialog.h \
		../../5.7/gcc_64/include/QtWidgets/qwidget.h \
		../../5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../5.7/gcc_64/include/QtCore/qglobal.h \
		../../5.7/gcc_64/include/QtCore/qconfig.h \
		../../5.7/gcc_64/include/QtCore/qfeatures.h \
		../../5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../5.7/gcc_64/include/QtCore/qisenum.h \
		../../5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../5.7/gcc_64/include/QtCore/qlogging.h \
		../../5.7/gcc_64/include/QtCore/qflags.h \
		../../5.7/gcc_64/include/QtCore/qatomic.h \
		../../5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../5.7/gcc_64/include/QtCore/qmutex.h \
		../../5.7/gcc_64/include/QtCore/qnumeric.h \
		../../5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../5.7/gcc_64/include/QtCore/qnamespace.h \
		../../5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../5.7/gcc_64/include/QtCore/qobject.h \
		../../5.7/gcc_64/include/QtCore/qstring.h \
		../../5.7/gcc_64/include/QtCore/qchar.h \
		../../5.7/gcc_64/include/QtCore/qbytearray.h \
		../../5.7/gcc_64/include/QtCore/qrefcount.h \
		../../5.7/gcc_64/include/QtCore/qarraydata.h \
		../../5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../5.7/gcc_64/include/QtCore/qlist.h \
		../../5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../5.7/gcc_64/include/QtCore/qiterator.h \
		../../5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../5.7/gcc_64/include/QtCore/qpair.h \
		../../5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../5.7/gcc_64/include/QtCore/qstringlist.h \
		../../5.7/gcc_64/include/QtCore/qregexp.h \
		../../5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../5.7/gcc_64/include/QtCore/qmetatype.h \
		../../5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../5.7/gcc_64/include/QtCore/qmargins.h \
		../../5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../5.7/gcc_64/include/QtCore/qrect.h \
		../../5.7/gcc_64/include/QtCore/qsize.h \
		../../5.7/gcc_64/include/QtCore/qpoint.h \
		../../5.7/gcc_64/include/QtGui/qpalette.h \
		../../5.7/gcc_64/include/QtGui/qcolor.h \
		../../5.7/gcc_64/include/QtGui/qrgb.h \
		../../5.7/gcc_64/include/QtGui/qrgba64.h \
		../../5.7/gcc_64/include/QtGui/qbrush.h \
		../../5.7/gcc_64/include/QtCore/qvector.h \
		../../5.7/gcc_64/include/QtGui/qmatrix.h \
		../../5.7/gcc_64/include/QtGui/qpolygon.h \
		../../5.7/gcc_64/include/QtGui/qregion.h \
		../../5.7/gcc_64/include/QtCore/qdatastream.h \
		../../5.7/gcc_64/include/QtCore/qiodevice.h \
		../../5.7/gcc_64/include/QtCore/qline.h \
		../../5.7/gcc_64/include/QtGui/qtransform.h \
		../../5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../5.7/gcc_64/include/QtGui/qimage.h \
		../../5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../5.7/gcc_64/include/QtGui/qpixmap.h \
		../../5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../5.7/gcc_64/include/QtCore/qshareddata.h \
		../../5.7/gcc_64/include/QtCore/qhash.h \
		../../5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../5.7/gcc_64/include/QtGui/qfont.h \
		../../5.7/gcc_64/include/QtGui/qfontmetrics.h \
		../../5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../5.7/gcc_64/include/QtGui/qcursor.h \
		../../5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../5.7/gcc_64/include/QtGui/qevent.h \
		../../5.7/gcc_64/include/QtCore/qvariant.h \
		../../5.7/gcc_64/include/QtCore/qmap.h \
		../../5.7/gcc_64/include/QtCore/qdebug.h \
		../../5.7/gcc_64/include/QtCore/qtextstream.h \
		../../5.7/gcc_64/include/QtCore/qlocale.h \
		../../5.7/gcc_64/include/QtCore/qset.h \
		../../5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../5.7/gcc_64/include/QtCore/qurl.h \
		../../5.7/gcc_64/include/QtCore/qurlquery.h \
		../../5.7/gcc_64/include/QtCore/qfile.h \
		../../5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../5.7/gcc_64/include/QtGui/qvector2d.h \
		../../5.7/gcc_64/include/QtGui/qtouchdevice.h \
		successdialog.h \
		../../5.7/gcc_64/bin/moc
	/home/best/Qt5.7.0/5.7/gcc_64/bin/moc $(DEFINES) -I/home/best/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++ -I/home/best/Qt5.7.0/Workspace/screenshot -I/home/best/Qt5.7.0/5.7/gcc_64/include -I/home/best/Qt5.7.0/5.7/gcc_64/include/QtWidgets -I/home/best/Qt5.7.0/5.7/gcc_64/include/QtGui -I/home/best/Qt5.7.0/5.7/gcc_64/include/QtNetwork -I/home/best/Qt5.7.0/5.7/gcc_64/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include successdialog.h -o moc_successdialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_form.h ui_successdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_form.h ui_successdialog.h
ui_form.h: form.ui \
		../../5.7/gcc_64/bin/uic
	/home/best/Qt5.7.0/5.7/gcc_64/bin/uic form.ui -o ui_form.h

ui_successdialog.h: successdialog.ui \
		../../5.7/gcc_64/bin/uic
	/home/best/Qt5.7.0/5.7/gcc_64/bin/uic successdialog.ui -o ui_successdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ../../5.7/gcc_64/include/QtWidgets/QApplication \
		../../5.7/gcc_64/include/QtWidgets/qapplication.h \
		../../5.7/gcc_64/include/QtCore/qcoreapplication.h \
		../../5.7/gcc_64/include/QtCore/qglobal.h \
		../../5.7/gcc_64/include/QtCore/qconfig.h \
		../../5.7/gcc_64/include/QtCore/qfeatures.h \
		../../5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../5.7/gcc_64/include/QtCore/qisenum.h \
		../../5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../5.7/gcc_64/include/QtCore/qlogging.h \
		../../5.7/gcc_64/include/QtCore/qflags.h \
		../../5.7/gcc_64/include/QtCore/qatomic.h \
		../../5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../5.7/gcc_64/include/QtCore/qmutex.h \
		../../5.7/gcc_64/include/QtCore/qnumeric.h \
		../../5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../5.7/gcc_64/include/QtCore/qstring.h \
		../../5.7/gcc_64/include/QtCore/qchar.h \
		../../5.7/gcc_64/include/QtCore/qbytearray.h \
		../../5.7/gcc_64/include/QtCore/qrefcount.h \
		../../5.7/gcc_64/include/QtCore/qnamespace.h \
		../../5.7/gcc_64/include/QtCore/qarraydata.h \
		../../5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../5.7/gcc_64/include/QtCore/qobject.h \
		../../5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../5.7/gcc_64/include/QtCore/qlist.h \
		../../5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../5.7/gcc_64/include/QtCore/qiterator.h \
		../../5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../5.7/gcc_64/include/QtCore/qpair.h \
		../../5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../5.7/gcc_64/include/QtCore/qstringlist.h \
		../../5.7/gcc_64/include/QtCore/qregexp.h \
		../../5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../5.7/gcc_64/include/QtCore/qmetatype.h \
		../../5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../5.7/gcc_64/include/QtCore/qeventloop.h \
		../../5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../5.7/gcc_64/include/QtCore/qpoint.h \
		../../5.7/gcc_64/include/QtCore/qsize.h \
		../../5.7/gcc_64/include/QtGui/qcursor.h \
		../../5.7/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../5.7/gcc_64/include/QtWidgets/qwidget.h \
		../../5.7/gcc_64/include/QtCore/qmargins.h \
		../../5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../5.7/gcc_64/include/QtCore/qrect.h \
		../../5.7/gcc_64/include/QtGui/qpalette.h \
		../../5.7/gcc_64/include/QtGui/qcolor.h \
		../../5.7/gcc_64/include/QtGui/qrgb.h \
		../../5.7/gcc_64/include/QtGui/qrgba64.h \
		../../5.7/gcc_64/include/QtGui/qbrush.h \
		../../5.7/gcc_64/include/QtCore/qvector.h \
		../../5.7/gcc_64/include/QtGui/qmatrix.h \
		../../5.7/gcc_64/include/QtGui/qpolygon.h \
		../../5.7/gcc_64/include/QtGui/qregion.h \
		../../5.7/gcc_64/include/QtCore/qdatastream.h \
		../../5.7/gcc_64/include/QtCore/qiodevice.h \
		../../5.7/gcc_64/include/QtCore/qline.h \
		../../5.7/gcc_64/include/QtGui/qtransform.h \
		../../5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../5.7/gcc_64/include/QtGui/qimage.h \
		../../5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../5.7/gcc_64/include/QtGui/qpixmap.h \
		../../5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../5.7/gcc_64/include/QtCore/qshareddata.h \
		../../5.7/gcc_64/include/QtCore/qhash.h \
		../../5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../5.7/gcc_64/include/QtGui/qfont.h \
		../../5.7/gcc_64/include/QtGui/qfontmetrics.h \
		../../5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../5.7/gcc_64/include/QtGui/qevent.h \
		../../5.7/gcc_64/include/QtCore/qvariant.h \
		../../5.7/gcc_64/include/QtCore/qmap.h \
		../../5.7/gcc_64/include/QtCore/qdebug.h \
		../../5.7/gcc_64/include/QtCore/qtextstream.h \
		../../5.7/gcc_64/include/QtCore/qlocale.h \
		../../5.7/gcc_64/include/QtCore/qset.h \
		../../5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../5.7/gcc_64/include/QtCore/qurl.h \
		../../5.7/gcc_64/include/QtCore/qurlquery.h \
		../../5.7/gcc_64/include/QtCore/qfile.h \
		../../5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../5.7/gcc_64/include/QtGui/qvector2d.h \
		../../5.7/gcc_64/include/QtGui/qtouchdevice.h \
		../../5.7/gcc_64/include/QtGui/qguiapplication.h \
		../../5.7/gcc_64/include/QtGui/qinputmethod.h \
		form.h \
		../../5.7/gcc_64/include/QtWidgets/QWidget \
		../../5.7/gcc_64/include/QtCore/QDebug \
		../../5.7/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../../5.7/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../5.7/gcc_64/include/QtCore/QObject \
		../../5.7/gcc_64/include/QtNetwork/QSslConfiguration \
		../../5.7/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../../5.7/gcc_64/include/QtNetwork/qsslsocket.h \
		../../5.7/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../5.7/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../5.7/gcc_64/include/QtNetwork/qsslerror.h \
		../../5.7/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../5.7/gcc_64/include/QtCore/qcryptographichash.h \
		../../5.7/gcc_64/include/QtCore/qdatetime.h \
		../../5.7/gcc_64/include/QtNetwork/qssl.h \
		../../5.7/gcc_64/include/QtCore/QFlags \
		../../5.7/gcc_64/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../5.7/gcc_64/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../5.7/gcc_64/include/QtCore/QtGlobal \
		../../5.7/gcc_64/include/QtCore/QString \
		../../5.7/gcc_64/include/QtCore/QSharedDataPointer \
		../../5.7/gcc_64/include/QtCore/QMetaType \
		../../5.7/gcc_64/include/QtNetwork/QHttpMultiPart \
		../../5.7/gcc_64/include/QtNetwork/qhttpmultipart.h \
		../../5.7/gcc_64/include/QtCore/QByteArray \
		../../5.7/gcc_64/include/QtCore/QIODevice \
		../../5.7/gcc_64/include/QtNetwork/QNetworkRequest \
		../../5.7/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../../5.7/gcc_64/include/QtCore/QUrl \
		../../5.7/gcc_64/include/QtCore/QVariant \
		../../5.7/gcc_64/include/QtNetwork/QHttpPart \
		../../5.7/gcc_64/include/QtCore/QFile \
		../../5.7/gcc_64/include/QtNetwork/QNetworkReply \
		../../5.7/gcc_64/include/QtNetwork/qnetworkreply.h \
		../../5.7/gcc_64/include/QtNetwork/QSslSocket \
		../../5.7/gcc_64/include/QtWidgets/QStyle \
		../../5.7/gcc_64/include/QtWidgets/qstyle.h \
		../../5.7/gcc_64/include/QtGui/qicon.h \
		../../5.7/gcc_64/include/QtWidgets/QDesktopWidget \
		../../5.7/gcc_64/include/QtCore/QCommandLineParser \
		../../5.7/gcc_64/include/QtCore/qcommandlineparser.h \
		../../5.7/gcc_64/include/QtCore/qcommandlineoption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

form.o: form.cpp ../../5.7/gcc_64/include/QtWidgets/QApplication \
		../../5.7/gcc_64/include/QtWidgets/qapplication.h \
		../../5.7/gcc_64/include/QtCore/qcoreapplication.h \
		../../5.7/gcc_64/include/QtCore/qglobal.h \
		../../5.7/gcc_64/include/QtCore/qconfig.h \
		../../5.7/gcc_64/include/QtCore/qfeatures.h \
		../../5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../5.7/gcc_64/include/QtCore/qisenum.h \
		../../5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../5.7/gcc_64/include/QtCore/qlogging.h \
		../../5.7/gcc_64/include/QtCore/qflags.h \
		../../5.7/gcc_64/include/QtCore/qatomic.h \
		../../5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../5.7/gcc_64/include/QtCore/qmutex.h \
		../../5.7/gcc_64/include/QtCore/qnumeric.h \
		../../5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../5.7/gcc_64/include/QtCore/qstring.h \
		../../5.7/gcc_64/include/QtCore/qchar.h \
		../../5.7/gcc_64/include/QtCore/qbytearray.h \
		../../5.7/gcc_64/include/QtCore/qrefcount.h \
		../../5.7/gcc_64/include/QtCore/qnamespace.h \
		../../5.7/gcc_64/include/QtCore/qarraydata.h \
		../../5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../5.7/gcc_64/include/QtCore/qobject.h \
		../../5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../5.7/gcc_64/include/QtCore/qlist.h \
		../../5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../5.7/gcc_64/include/QtCore/qiterator.h \
		../../5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../5.7/gcc_64/include/QtCore/qpair.h \
		../../5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../5.7/gcc_64/include/QtCore/qstringlist.h \
		../../5.7/gcc_64/include/QtCore/qregexp.h \
		../../5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../5.7/gcc_64/include/QtCore/qmetatype.h \
		../../5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../5.7/gcc_64/include/QtCore/qeventloop.h \
		../../5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../5.7/gcc_64/include/QtCore/qpoint.h \
		../../5.7/gcc_64/include/QtCore/qsize.h \
		../../5.7/gcc_64/include/QtGui/qcursor.h \
		../../5.7/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../5.7/gcc_64/include/QtWidgets/qwidget.h \
		../../5.7/gcc_64/include/QtCore/qmargins.h \
		../../5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../5.7/gcc_64/include/QtCore/qrect.h \
		../../5.7/gcc_64/include/QtGui/qpalette.h \
		../../5.7/gcc_64/include/QtGui/qcolor.h \
		../../5.7/gcc_64/include/QtGui/qrgb.h \
		../../5.7/gcc_64/include/QtGui/qrgba64.h \
		../../5.7/gcc_64/include/QtGui/qbrush.h \
		../../5.7/gcc_64/include/QtCore/qvector.h \
		../../5.7/gcc_64/include/QtGui/qmatrix.h \
		../../5.7/gcc_64/include/QtGui/qpolygon.h \
		../../5.7/gcc_64/include/QtGui/qregion.h \
		../../5.7/gcc_64/include/QtCore/qdatastream.h \
		../../5.7/gcc_64/include/QtCore/qiodevice.h \
		../../5.7/gcc_64/include/QtCore/qline.h \
		../../5.7/gcc_64/include/QtGui/qtransform.h \
		../../5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../5.7/gcc_64/include/QtGui/qimage.h \
		../../5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../5.7/gcc_64/include/QtGui/qpixmap.h \
		../../5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../5.7/gcc_64/include/QtCore/qshareddata.h \
		../../5.7/gcc_64/include/QtCore/qhash.h \
		../../5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../5.7/gcc_64/include/QtGui/qfont.h \
		../../5.7/gcc_64/include/QtGui/qfontmetrics.h \
		../../5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../5.7/gcc_64/include/QtGui/qevent.h \
		../../5.7/gcc_64/include/QtCore/qvariant.h \
		../../5.7/gcc_64/include/QtCore/qmap.h \
		../../5.7/gcc_64/include/QtCore/qdebug.h \
		../../5.7/gcc_64/include/QtCore/qtextstream.h \
		../../5.7/gcc_64/include/QtCore/qlocale.h \
		../../5.7/gcc_64/include/QtCore/qset.h \
		../../5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../5.7/gcc_64/include/QtCore/qurl.h \
		../../5.7/gcc_64/include/QtCore/qurlquery.h \
		../../5.7/gcc_64/include/QtCore/qfile.h \
		../../5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../5.7/gcc_64/include/QtGui/qvector2d.h \
		../../5.7/gcc_64/include/QtGui/qtouchdevice.h \
		../../5.7/gcc_64/include/QtGui/qguiapplication.h \
		../../5.7/gcc_64/include/QtGui/qinputmethod.h \
		../../5.7/gcc_64/include/QtGui/QWindow \
		../../5.7/gcc_64/include/QtGui/qwindow.h \
		../../5.7/gcc_64/include/QtCore/QObject \
		../../5.7/gcc_64/include/QtCore/QEvent \
		../../5.7/gcc_64/include/QtCore/QMargins \
		../../5.7/gcc_64/include/QtCore/QRect \
		../../5.7/gcc_64/include/QtGui/qsurface.h \
		../../5.7/gcc_64/include/QtGui/qsurfaceformat.h \
		../../5.7/gcc_64/include/QtGui/qicon.h \
		../../5.7/gcc_64/include/QtGui/QScreen \
		../../5.7/gcc_64/include/QtGui/qscreen.h \
		../../5.7/gcc_64/include/QtCore/QList \
		../../5.7/gcc_64/include/QtCore/QSize \
		../../5.7/gcc_64/include/QtCore/QSizeF \
		../../5.7/gcc_64/include/QtGui/QTransform \
		../../5.7/gcc_64/include/QtCore/QDateTime \
		../../5.7/gcc_64/include/QtCore/qdatetime.h \
		../../5.7/gcc_64/include/QtWidgets/QMessageBox \
		../../5.7/gcc_64/include/QtWidgets/qmessagebox.h \
		../../5.7/gcc_64/include/QtWidgets/qdialog.h \
		../../5.7/gcc_64/include/QtCore/QDir \
		../../5.7/gcc_64/include/QtCore/qdir.h \
		../../5.7/gcc_64/include/QtCore/qfileinfo.h \
		form.h \
		../../5.7/gcc_64/include/QtWidgets/QWidget \
		../../5.7/gcc_64/include/QtCore/QDebug \
		../../5.7/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../../5.7/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../5.7/gcc_64/include/QtNetwork/QSslConfiguration \
		../../5.7/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../../5.7/gcc_64/include/QtNetwork/qsslsocket.h \
		../../5.7/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../5.7/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../5.7/gcc_64/include/QtNetwork/qsslerror.h \
		../../5.7/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../5.7/gcc_64/include/QtCore/qcryptographichash.h \
		../../5.7/gcc_64/include/QtNetwork/qssl.h \
		../../5.7/gcc_64/include/QtCore/QFlags \
		../../5.7/gcc_64/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../5.7/gcc_64/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../5.7/gcc_64/include/QtCore/QtGlobal \
		../../5.7/gcc_64/include/QtCore/QString \
		../../5.7/gcc_64/include/QtCore/QSharedDataPointer \
		../../5.7/gcc_64/include/QtCore/QMetaType \
		../../5.7/gcc_64/include/QtNetwork/QHttpMultiPart \
		../../5.7/gcc_64/include/QtNetwork/qhttpmultipart.h \
		../../5.7/gcc_64/include/QtCore/QByteArray \
		../../5.7/gcc_64/include/QtCore/QIODevice \
		../../5.7/gcc_64/include/QtNetwork/QNetworkRequest \
		../../5.7/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../../5.7/gcc_64/include/QtCore/QUrl \
		../../5.7/gcc_64/include/QtCore/QVariant \
		../../5.7/gcc_64/include/QtNetwork/QHttpPart \
		../../5.7/gcc_64/include/QtCore/QFile \
		../../5.7/gcc_64/include/QtNetwork/QNetworkReply \
		../../5.7/gcc_64/include/QtNetwork/qnetworkreply.h \
		../../5.7/gcc_64/include/QtNetwork/QSslSocket \
		ui_form.h \
		../../5.7/gcc_64/include/QtCore/QRegExp \
		successdialog.h \
		../../5.7/gcc_64/include/QtWidgets/QDialog
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o form.o form.cpp

successdialog.o: successdialog.cpp successdialog.h \
		../../5.7/gcc_64/include/QtWidgets/QDialog \
		../../5.7/gcc_64/include/QtWidgets/qdialog.h \
		../../5.7/gcc_64/include/QtWidgets/qwidget.h \
		../../5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../5.7/gcc_64/include/QtCore/qglobal.h \
		../../5.7/gcc_64/include/QtCore/qconfig.h \
		../../5.7/gcc_64/include/QtCore/qfeatures.h \
		../../5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../5.7/gcc_64/include/QtCore/qisenum.h \
		../../5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../5.7/gcc_64/include/QtCore/qlogging.h \
		../../5.7/gcc_64/include/QtCore/qflags.h \
		../../5.7/gcc_64/include/QtCore/qatomic.h \
		../../5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../5.7/gcc_64/include/QtCore/qmutex.h \
		../../5.7/gcc_64/include/QtCore/qnumeric.h \
		../../5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../5.7/gcc_64/include/QtCore/qnamespace.h \
		../../5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../5.7/gcc_64/include/QtCore/qobject.h \
		../../5.7/gcc_64/include/QtCore/qstring.h \
		../../5.7/gcc_64/include/QtCore/qchar.h \
		../../5.7/gcc_64/include/QtCore/qbytearray.h \
		../../5.7/gcc_64/include/QtCore/qrefcount.h \
		../../5.7/gcc_64/include/QtCore/qarraydata.h \
		../../5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../5.7/gcc_64/include/QtCore/qlist.h \
		../../5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../5.7/gcc_64/include/QtCore/qiterator.h \
		../../5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../5.7/gcc_64/include/QtCore/qpair.h \
		../../5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../5.7/gcc_64/include/QtCore/qstringlist.h \
		../../5.7/gcc_64/include/QtCore/qregexp.h \
		../../5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../5.7/gcc_64/include/QtCore/qmetatype.h \
		../../5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../5.7/gcc_64/include/QtCore/qmargins.h \
		../../5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../5.7/gcc_64/include/QtCore/qrect.h \
		../../5.7/gcc_64/include/QtCore/qsize.h \
		../../5.7/gcc_64/include/QtCore/qpoint.h \
		../../5.7/gcc_64/include/QtGui/qpalette.h \
		../../5.7/gcc_64/include/QtGui/qcolor.h \
		../../5.7/gcc_64/include/QtGui/qrgb.h \
		../../5.7/gcc_64/include/QtGui/qrgba64.h \
		../../5.7/gcc_64/include/QtGui/qbrush.h \
		../../5.7/gcc_64/include/QtCore/qvector.h \
		../../5.7/gcc_64/include/QtGui/qmatrix.h \
		../../5.7/gcc_64/include/QtGui/qpolygon.h \
		../../5.7/gcc_64/include/QtGui/qregion.h \
		../../5.7/gcc_64/include/QtCore/qdatastream.h \
		../../5.7/gcc_64/include/QtCore/qiodevice.h \
		../../5.7/gcc_64/include/QtCore/qline.h \
		../../5.7/gcc_64/include/QtGui/qtransform.h \
		../../5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../5.7/gcc_64/include/QtGui/qimage.h \
		../../5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../5.7/gcc_64/include/QtGui/qpixmap.h \
		../../5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../5.7/gcc_64/include/QtCore/qshareddata.h \
		../../5.7/gcc_64/include/QtCore/qhash.h \
		../../5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../5.7/gcc_64/include/QtGui/qfont.h \
		../../5.7/gcc_64/include/QtGui/qfontmetrics.h \
		../../5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../5.7/gcc_64/include/QtGui/qcursor.h \
		../../5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../5.7/gcc_64/include/QtGui/qevent.h \
		../../5.7/gcc_64/include/QtCore/qvariant.h \
		../../5.7/gcc_64/include/QtCore/qmap.h \
		../../5.7/gcc_64/include/QtCore/qdebug.h \
		../../5.7/gcc_64/include/QtCore/qtextstream.h \
		../../5.7/gcc_64/include/QtCore/qlocale.h \
		../../5.7/gcc_64/include/QtCore/qset.h \
		../../5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../5.7/gcc_64/include/QtCore/qurl.h \
		../../5.7/gcc_64/include/QtCore/qurlquery.h \
		../../5.7/gcc_64/include/QtCore/qfile.h \
		../../5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../5.7/gcc_64/include/QtGui/qvector2d.h \
		../../5.7/gcc_64/include/QtGui/qtouchdevice.h \
		ui_successdialog.h \
		../../5.7/gcc_64/include/QtGui/QClipboard \
		../../5.7/gcc_64/include/QtGui/qclipboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o successdialog.o successdialog.cpp

moc_form.o: moc_form.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_form.o moc_form.cpp

moc_successdialog.o: moc_successdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_successdialog.o moc_successdialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

